version: '3.1'
name: quest_deep_orderbook
services:
  quest_deep_orderbook:
    image: quest_deep_orderbook
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - questdb
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      BINANCE_API_KEY_FILE: /run/secrets/binance_api_key
      BINANCE_API_SECRET_FILE: /run/secrets/binance_secret
      ORDERBOOK_DEPTH: 20
      QUEST_HOST: "127.0.0.1"
      QUEST_PORT: 9009
    secrets:
      - binance_api_key
      - binance_secret
  questdb:
    ports:
      - 9000:9000
      - 9009:9009
      - 8812:8812
      - 9003:9003
    volumes:
      - $PWD:/var/lib/questdb
    image: questdb/questdb:latest
secrets:
  binance_api_key:
    file: secrets/binance_api_key
  binance_secret:
    file: secrets/binance_secret